services:
  cdb:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata18:/var/lib/postgresql
    restart: "no"
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - '2500:2500'
      - '9000:9000'

volumes:
  pgdata18:
