version: '3.8'
services:
  cdb:
    image: mariadb
    ports:
      - "3366:3306"
    volumes:
      - isc:/var/lib/mysql
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: demo
      MARIADB_USER: demo
      MARIADB_PASSWORD: demo

  inbucket:
    image: inbucket/inbucket:latest
    ports:
      - '2500:2500'
      - '9000:9000'

volumes:
  isc:
